app/todos/__init__.py
from flask import Blueprint

todos = Blueprint("todo", __name__, template_folder="templates")

from app.todos import routes

app/todos/routes.py
from app import db

from flask import redirect, request, render_template, flash

from app.todos import todos
from app.models import Todo
from app.forms import AddTodo


@todos.route("/todo/<what_view>", methods=["GET", "POST"])
def todo_view(what_view):
    todos = Todo.query.filter_by(completed=False).all()
    form = AddTodo()

    if what_view.lower() == "completed_false":
        todos = Todo.query.filter_by(completed=False).all()
    if what_view.lower() == "completed_true":
        todos = Todo.query.filter_by(completed=True).all()

    if form.validate_on_submit():
        new_todo = Todo(
            text=form.text.data,
            priority=form.priority.data,
            deadline=form.deadline.data,
        )
        db.session.add(new_todo)
        db.session.commit()
        flash(f"New TODO added")
        return redirect(request.referrer)
    return render_template("todo.html", title="Todo", todos=todos, form=form)


@todos.route("/todo/<id>/change_status", methods=["GET", "POST"])
def change_status_todo(id):
    todo = Todo.query.get(id)
    todo.completed = not todo.completed
    db.session.commit()
    return redirect(request.referrer)


@todos.route("/todo/<id>/remove", methods=["GET", "POST"])
def remove_todo(id):
    db.session.query(Todo).filter_by(id=id).delete()
    db.session.commit()
    return redirect(request.referrer)

app/todos/templates/todo.html
{% extends "base.html" %}
{% block content %}
<script src="{{ url_for('static', filename='scripts.js') }}"></script>
<body>
  <a href="/todo/completed_true">Closed TODOs</a>
  <form action="" method="post" novalidate>
    <p>
      {{ form.hidden_tag() }}
      {{ form.text.label }}:{{ form.text(style='width:400px') }}
      {{ form.priority.label }}:{{ form.priority(style='height: 20px; width:100px') }}
      {{ form.deadline.label }}:{{ form.deadline() }}
      {{ form.submit() }} <br>
      {% for error in form.text.errors %}
        <span style="color: red;">{{ error }}</span>
      {% endfor %}
    </p>
  </form>
  <table>
    <thead>
      <tr>
        <th>No</th>
        <th>TODO</th>
        <th>Priority</th>
        <th>Deadline</th>
        <th>Created</th>
        <th>Completed?</th>
        <th>Remove</th>
      </tr>
    </thead>
    <tbody>
      {% for todo in todos %}
        {% if todo.deadline == current_date %}
          <tr style="background-color: red;">
        {% else %}
          <tr>
        {% endif %}
          <td>{{ loop.index }}</td>
          <td>{{ todo.text }}</td>
          <td>{{ todo.priority }}</td>
          <td>{{ todo.deadline }}</td>
          <td>{{ moment(todo.timestamp).format('DD/MM/YYYY') }}</td>      
          <td><a href="{{ url_for('todo.change_status_todo', id=todo.id) }}">{{ todo.completed }}</a></td>
          <td><a href="{{ url_for('todo.remove_todo', id=todo.id) }}">Remove</a></td>
        </tr> 
      {% endfor %}
    </tbody>
  </table>
</body>
{% endblock %}